// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file_transfer.proto
#ifndef GRPC_file_5ftransfer_2eproto__INCLUDED
#define GRPC_file_5ftransfer_2eproto__INCLUDED

#include "file_transfer.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace filetransfer {

class FileServer final {
 public:
  static constexpr char const* service_full_name() {
    return "filetransfer.FileServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status getSlice(::grpc::ClientContext* context, const ::filetransfer::SliceRequest& request, ::filetransfer::Slice* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::Slice>> AsyncgetSlice(::grpc::ClientContext* context, const ::filetransfer::SliceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::Slice>>(AsyncgetSliceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::Slice>> PrepareAsyncgetSlice(::grpc::ClientContext* context, const ::filetransfer::SliceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::Slice>>(PrepareAsyncgetSliceRaw(context, request, cq));
    }
    virtual ::grpc::Status getMetaData(::grpc::ClientContext* context, const ::filetransfer::FileName& request, ::filetransfer::FileMetadata* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::FileMetadata>> AsyncgetMetaData(::grpc::ClientContext* context, const ::filetransfer::FileName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::FileMetadata>>(AsyncgetMetaDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::FileMetadata>> PrepareAsyncgetMetaData(::grpc::ClientContext* context, const ::filetransfer::FileName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::FileMetadata>>(PrepareAsyncgetMetaDataRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void getSlice(::grpc::ClientContext* context, const ::filetransfer::SliceRequest* request, ::filetransfer::Slice* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void getSlice(::grpc::ClientContext* context, const ::filetransfer::SliceRequest* request, ::filetransfer::Slice* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void getSlice(::grpc::ClientContext* context, const ::filetransfer::SliceRequest* request, ::filetransfer::Slice* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void getMetaData(::grpc::ClientContext* context, const ::filetransfer::FileName* request, ::filetransfer::FileMetadata* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void getMetaData(::grpc::ClientContext* context, const ::filetransfer::FileName* request, ::filetransfer::FileMetadata* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void getMetaData(::grpc::ClientContext* context, const ::filetransfer::FileName* request, ::filetransfer::FileMetadata* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::Slice>* AsyncgetSliceRaw(::grpc::ClientContext* context, const ::filetransfer::SliceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::Slice>* PrepareAsyncgetSliceRaw(::grpc::ClientContext* context, const ::filetransfer::SliceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::FileMetadata>* AsyncgetMetaDataRaw(::grpc::ClientContext* context, const ::filetransfer::FileName& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::FileMetadata>* PrepareAsyncgetMetaDataRaw(::grpc::ClientContext* context, const ::filetransfer::FileName& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status getSlice(::grpc::ClientContext* context, const ::filetransfer::SliceRequest& request, ::filetransfer::Slice* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::Slice>> AsyncgetSlice(::grpc::ClientContext* context, const ::filetransfer::SliceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::Slice>>(AsyncgetSliceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::Slice>> PrepareAsyncgetSlice(::grpc::ClientContext* context, const ::filetransfer::SliceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::Slice>>(PrepareAsyncgetSliceRaw(context, request, cq));
    }
    ::grpc::Status getMetaData(::grpc::ClientContext* context, const ::filetransfer::FileName& request, ::filetransfer::FileMetadata* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::FileMetadata>> AsyncgetMetaData(::grpc::ClientContext* context, const ::filetransfer::FileName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::FileMetadata>>(AsyncgetMetaDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::FileMetadata>> PrepareAsyncgetMetaData(::grpc::ClientContext* context, const ::filetransfer::FileName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::FileMetadata>>(PrepareAsyncgetMetaDataRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void getSlice(::grpc::ClientContext* context, const ::filetransfer::SliceRequest* request, ::filetransfer::Slice* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void getSlice(::grpc::ClientContext* context, const ::filetransfer::SliceRequest* request, ::filetransfer::Slice* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void getSlice(::grpc::ClientContext* context, const ::filetransfer::SliceRequest* request, ::filetransfer::Slice* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void getMetaData(::grpc::ClientContext* context, const ::filetransfer::FileName* request, ::filetransfer::FileMetadata* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void getMetaData(::grpc::ClientContext* context, const ::filetransfer::FileName* request, ::filetransfer::FileMetadata* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void getMetaData(::grpc::ClientContext* context, const ::filetransfer::FileName* request, ::filetransfer::FileMetadata* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::filetransfer::Slice>* AsyncgetSliceRaw(::grpc::ClientContext* context, const ::filetransfer::SliceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::filetransfer::Slice>* PrepareAsyncgetSliceRaw(::grpc::ClientContext* context, const ::filetransfer::SliceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::filetransfer::FileMetadata>* AsyncgetMetaDataRaw(::grpc::ClientContext* context, const ::filetransfer::FileName& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::filetransfer::FileMetadata>* PrepareAsyncgetMetaDataRaw(::grpc::ClientContext* context, const ::filetransfer::FileName& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_getSlice_;
    const ::grpc::internal::RpcMethod rpcmethod_getMetaData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status getSlice(::grpc::ServerContext* context, const ::filetransfer::SliceRequest* request, ::filetransfer::Slice* response);
    virtual ::grpc::Status getMetaData(::grpc::ServerContext* context, const ::filetransfer::FileName* request, ::filetransfer::FileMetadata* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getSlice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getSlice() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getSlice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getSlice(::grpc::ServerContext* /*context*/, const ::filetransfer::SliceRequest* /*request*/, ::filetransfer::Slice* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetSlice(::grpc::ServerContext* context, ::filetransfer::SliceRequest* request, ::grpc::ServerAsyncResponseWriter< ::filetransfer::Slice>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_getMetaData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getMetaData() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_getMetaData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getMetaData(::grpc::ServerContext* /*context*/, const ::filetransfer::FileName* /*request*/, ::filetransfer::FileMetadata* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetMetaData(::grpc::ServerContext* context, ::filetransfer::FileName* request, ::grpc::ServerAsyncResponseWriter< ::filetransfer::FileMetadata>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getSlice<WithAsyncMethod_getMetaData<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_getSlice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_getSlice() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::filetransfer::SliceRequest, ::filetransfer::Slice>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::filetransfer::SliceRequest* request, ::filetransfer::Slice* response) { return this->getSlice(context, request, response); }));}
    void SetMessageAllocatorFor_getSlice(
        ::grpc::experimental::MessageAllocator< ::filetransfer::SliceRequest, ::filetransfer::Slice>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::filetransfer::SliceRequest, ::filetransfer::Slice>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_getSlice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getSlice(::grpc::ServerContext* /*context*/, const ::filetransfer::SliceRequest* /*request*/, ::filetransfer::Slice* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getSlice(
      ::grpc::CallbackServerContext* /*context*/, const ::filetransfer::SliceRequest* /*request*/, ::filetransfer::Slice* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getSlice(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::filetransfer::SliceRequest* /*request*/, ::filetransfer::Slice* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_getMetaData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_getMetaData() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::filetransfer::FileName, ::filetransfer::FileMetadata>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::filetransfer::FileName* request, ::filetransfer::FileMetadata* response) { return this->getMetaData(context, request, response); }));}
    void SetMessageAllocatorFor_getMetaData(
        ::grpc::experimental::MessageAllocator< ::filetransfer::FileName, ::filetransfer::FileMetadata>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::filetransfer::FileName, ::filetransfer::FileMetadata>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_getMetaData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getMetaData(::grpc::ServerContext* /*context*/, const ::filetransfer::FileName* /*request*/, ::filetransfer::FileMetadata* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getMetaData(
      ::grpc::CallbackServerContext* /*context*/, const ::filetransfer::FileName* /*request*/, ::filetransfer::FileMetadata* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getMetaData(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::filetransfer::FileName* /*request*/, ::filetransfer::FileMetadata* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_getSlice<ExperimentalWithCallbackMethod_getMetaData<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_getSlice<ExperimentalWithCallbackMethod_getMetaData<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_getSlice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getSlice() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getSlice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getSlice(::grpc::ServerContext* /*context*/, const ::filetransfer::SliceRequest* /*request*/, ::filetransfer::Slice* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_getMetaData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getMetaData() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_getMetaData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getMetaData(::grpc::ServerContext* /*context*/, const ::filetransfer::FileName* /*request*/, ::filetransfer::FileMetadata* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_getSlice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getSlice() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_getSlice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getSlice(::grpc::ServerContext* /*context*/, const ::filetransfer::SliceRequest* /*request*/, ::filetransfer::Slice* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetSlice(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_getMetaData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getMetaData() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_getMetaData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getMetaData(::grpc::ServerContext* /*context*/, const ::filetransfer::FileName* /*request*/, ::filetransfer::FileMetadata* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetMetaData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_getSlice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_getSlice() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getSlice(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_getSlice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getSlice(::grpc::ServerContext* /*context*/, const ::filetransfer::SliceRequest* /*request*/, ::filetransfer::Slice* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getSlice(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getSlice(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_getMetaData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_getMetaData() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getMetaData(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_getMetaData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getMetaData(::grpc::ServerContext* /*context*/, const ::filetransfer::FileName* /*request*/, ::filetransfer::FileMetadata* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getMetaData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getMetaData(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getSlice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getSlice() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::filetransfer::SliceRequest, ::filetransfer::Slice>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::filetransfer::SliceRequest, ::filetransfer::Slice>* streamer) {
                       return this->StreamedgetSlice(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getSlice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getSlice(::grpc::ServerContext* /*context*/, const ::filetransfer::SliceRequest* /*request*/, ::filetransfer::Slice* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetSlice(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::filetransfer::SliceRequest,::filetransfer::Slice>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getMetaData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getMetaData() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::filetransfer::FileName, ::filetransfer::FileMetadata>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::filetransfer::FileName, ::filetransfer::FileMetadata>* streamer) {
                       return this->StreamedgetMetaData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getMetaData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getMetaData(::grpc::ServerContext* /*context*/, const ::filetransfer::FileName* /*request*/, ::filetransfer::FileMetadata* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetMetaData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::filetransfer::FileName,::filetransfer::FileMetadata>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getSlice<WithStreamedUnaryMethod_getMetaData<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getSlice<WithStreamedUnaryMethod_getMetaData<Service > > StreamedService;
};

}  // namespace filetransfer


#endif  // GRPC_file_5ftransfer_2eproto__INCLUDED
